### ISSUE TITLE
Cannot run the command for reproducing

### ISSUE THREAD

**Issue by fiberleif** [jjljkjljk/EG-MCTS#1]
Hi, Authors,

Thanks for your excellent work and for sharing the codebase. l am reading your code but when l run the following command to reproduce the results: python EG_MCTS_plan.py --use_value_fn.  The error happens:
from eg_mcts.arg.parse_args import args  #no args found. 

![image](https://user-images.githubusercontent.com/11922971/185099911-8678f337-c151-43eb-a483-1a116e37b07c.png)

Can you help check this problem? Thank you!

**Comment by zemanet2020** [comment]
I had problems with EG_MCTS_plan.py, too.
I installed EG-MCTS as instructed in README as below.
But I got errors when running EG_MCTS_plan.py.
What could be a problem?

```

$ git clone https://github.com/jjljkjljk/EG-MCTS.git
$ cd EG-MCTS/
$ conda env create -f environment.yml
$ activate eg_mcts

$ pip install -e eg_mcts/packages/mlp_retrosyn
$ pip install -e eg_mcts/packages/rdchiral
$ pip install -e .

# Downloaded dataset and one_step_model from gdrive and unzipped them in eg_mcts directory.
$ cd eg_mcts
$ unzip one_step_model-20230428T170751Z-001.zip
$ unzip dataset-20230428T170741Z-001.zip
$ unzip dataset-20230428T170741Z-002.zip

$ python EG_MCTS_plan.py

root        : INFO     Loading building blocks from dataset/origin_dict.csv
root        : INFO     totally 23081629 building blocks loaded
root        : INFO     180 routes extracted from dataset/emol_test_data.txt loaded
root        : INFO     Templates: one_step_model/template_rules_1.dat
root        : INFO     Loading one-step-retrosynthetic model from one_step_model/retro_star_value_ours.ckpt
template rules: 381302it [00:00, 1502839.74it/s]
use_value_fn
root        : INFO     Loading Experience Guidance Network from saved_EG_fn/best_egn_for_emol.pt
Traceback (most recent call last):
  File "./EG_MCTS_plan.py", line 177, in <module>
    EG_MCTS_plan()
  File "./EG_MCTS_plan.py", line 48, in EG_MCTS_plan
    model.load_state_dict(torch.load(model_f,  map_location=device))
  File "/opt/anaconda/envs/eg_mcts/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda/envs/eg_mcts/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x1f'.

```
